### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by Jqiangwf** [LinkFlyWind/LeamETH#1]
您好，我想系统的学习区块链的智能合约开发，我之前是做iOS开发的，对于JS和React接触的很少，请问可以给我提一点学习的建议吗？

**Comment by qugang** [comment]
你好,javascript 和python 这两门语言是大的趋势,如果您的OC 或swift 掌握的很好的话,上手起来不是什么困难的事情,以太坊的智能合约的脚本引擎 使用的是javascript 引擎 目前没有其他语言的支持. 其实如果开发智能合约的话按照solidity 的规范去做就好了.我用truffle 因为 truffle 简化了很多开发的流程.

**Comment by Jqiangwf** [comment]
谢谢您的回答，能加您一个微信或者QQ吗？想在学习的过程中与您探讨和分享。

**Comment by qugang** [comment]
287551219
